In [42]:
import pandas as pd
import numpy as np
import re
import string
import nltk

In [43]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [44]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [45]:
fake_df = pd.read_csv("Fake.csv")
true_df = pd.read_csv("True.csv")

fake_df["label"] = 0
true_df["label"] = 1

news_df = pd.concat([fake_df, true_df], ignore_index=True)

news_df = news_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [46]:
!ls /content/drive/MyDrive

'Colab Notebooks'
'Personal Brand Digital Age - Final (1).gslides'
'Personal Brand Digital Age - Final (2).gslides'
'Personal Brand Digital Age - Final (3).gslides'
'Personal Brand Digital Age - Final Deck (1).gslides'
'Personal Brand Digital Age - Final Deck (2).gslides'
'Personal Brand Digital Age - Final Deck.gslides'
'Personal Brand Digital Age - Final.gslides'
'Personal Brand Digital Age Slides.gslides'
 preprocessed_news.csv
'SPM ECO System Proposal Defense (1).gslides'
'SPM ECO System Proposal Defense (2).gslides'
'SPM ECO System Proposal Defense.gslides'
'Untitled project (1).gscript'
'Untitled project (2).gscript'
'Untitled project (3).gscript'
'Untitled project (4).gscript'
'Untitled project (5).gscript'
'Untitled project.gscript'

In [47]:
news_df["content"] = news_df["title"] + " " + news_df["text"]

In [48]:
news_df[["content", "label"]].head()

                                             content  label
0  Ben Stein Calls Out 9th Circuit Court: Committ...      0
1  Trump drops Steve Bannon from National Securit...      1
2  Puerto Rico expects U.S. to lift Jones Act shi...      1
3   OOPS: Trump Just Accidentally Confirmed He Le...      0
4  Donald Trump heads for Scotland to reopen a go...      1

In [49]:
news_df["content"] = news_df["title"] + " " + news_df["text"]

news_df[["content", "label"]].head()

                                             content  label
0  Ben Stein Calls Out 9th Circuit Court: Committ...      0
1  Trump drops Steve Bannon from National Securit...      1
2  Puerto Rico expects U.S. to lift Jones Act shi...      1
3   OOPS: Trump Just Accidentally Confirmed He Le...      0
4  Donald Trump heads for Scotland to reopen a go...      1

In [50]:
news_df["content"] = news_df["content"].str.lower()

In [51]:
news_df[["content"]].head()

                                             content
0  ben stein calls out 9th circuit court: committ...
1  trump drops steve bannon from national securit...
2  puerto rico expects u.s. to lift jones act shi...
3   oops: trump just accidentally confirmed he le...
4  donald trump heads for scotland to reopen a go...

In [52]:
news_df["content"] = news_df["content"].str.lower()

news_df[["content"]].head()

                                             content
0  ben stein calls out 9th circuit court: committ...
1  trump drops steve bannon from national securit...
2  puerto rico expects u.s. to lift jones act shi...
3   oops: trump just accidentally confirmed he le...
4  donald trump heads for scotland to reopen a go...

In [53]:
def remove_urls(text):
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'www\S+', '', text)
    return text

In [54]:
news_df["content"] = news_df["content"].apply(remove_urls)

In [55]:
news_df[["content"]].head()

                                             content
0  ben stein calls out 9th circuit court: committ...
1  trump drops steve bannon from national securit...
2  puerto rico expects u.s. to lift jones act shi...
3   oops: trump just accidentally confirmed he le...
4  donald trump heads for scotland to reopen a go...

In [56]:
def remove_urls(text):
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'www\S+', '', text)
    return text

In [57]:
news_df["content"] = news_df["content"].apply(remove_urls)

In [58]:
news_df[["content"]].head()

                                             content
0  ben stein calls out 9th circuit court: committ...
1  trump drops steve bannon from national securit...
2  puerto rico expects u.s. to lift jones act shi...
3   oops: trump just accidentally confirmed he le...
4  donald trump heads for scotland to reopen a go...

In [59]:
def remove_html(text):
    return re.sub(r'<.*?>', '', text)

In [60]:
news_df["content"] = news_df["content"].apply(remove_html)

In [61]:
news_df[["content"]].head()

                                             content
0  ben stein calls out 9th circuit court: committ...
1  trump drops steve bannon from national securit...
2  puerto rico expects u.s. to lift jones act shi...
3   oops: trump just accidentally confirmed he le...
4  donald trump heads for scotland to reopen a go...

In [62]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [63]:
news_df["content"] = news_df["content"].apply(remove_punctuation)

In [64]:
news_df[["content"]].head()

                                             content
0  ben stein calls out 9th circuit court committe...
1  trump drops steve bannon from national securit...
2  puerto rico expects us to lift jones act shipp...
3   oops trump just accidentally confirmed he lea...
4  donald trump heads for scotland to reopen a go...

In [65]:
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

In [66]:
news_df["content"] = news_df["content"].apply(remove_numbers)

In [67]:
news_df[["content"]].head()

                                             content
0  ben stein calls out th circuit court committed...
1  trump drops steve bannon from national securit...
2  puerto rico expects us to lift jones act shipp...
3   oops trump just accidentally confirmed he lea...
4  donald trump heads for scotland to reopen a go...

In [68]:
news_df[["content"]].head()

                                             content
0  ben stein calls out th circuit court committed...
1  trump drops steve bannon from national securit...
2  puerto rico expects us to lift jones act shipp...
3   oops trump just accidentally confirmed he lea...
4  donald trump heads for scotland to reopen a go...

In [69]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [70]:
from nltk.tokenize import word_tokenize

news_df["tokens"] = news_df["content"].apply(word_tokenize)

In [71]:
import nltk

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [72]:
from nltk.tokenize import word_tokenize

news_df["tokens"] = news_df["content"].apply(word_tokenize)

news_df[["tokens"]].head()

                                              tokens
0  [ben, stein, calls, out, th, circuit, court, c...
1  [trump, drops, steve, bannon, from, national, ...
2  [puerto, rico, expects, us, to, lift, jones, a...
3  [oops, trump, just, accidentally, confirmed, h...
4  [donald, trump, heads, for, scotland, to, reop...

In [73]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [74]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

In [75]:
def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

In [76]:
news_df["tokens"] = news_df["tokens"].apply(remove_stopwords)

In [77]:
news_df[["tokens"]].head()

                                              tokens
0  [ben, stein, calls, th, circuit, court, commit...
1  [trump, drops, steve, bannon, national, securi...
2  [puerto, rico, expects, us, lift, jones, act, ...
3  [oops, trump, accidentally, confirmed, leaked,...
4  [donald, trump, heads, scotland, reopen, golf,...

In [78]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [79]:
def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

In [80]:
news_df["tokens"] = news_df["tokens"].apply(lemmatize_tokens)

In [81]:
news_df[["tokens"]].head()

                                              tokens
0  [ben, stein, call, th, circuit, court, committ...
1  [trump, drop, steve, bannon, national, securit...
2  [puerto, rico, expects, u, lift, jones, act, s...
3  [oops, trump, accidentally, confirmed, leaked,...
4  [donald, trump, head, scotland, reopen, golf, ...

In [82]:
news_df["clean_text"] = news_df["tokens"].apply(lambda x: " ".join(x))

In [83]:
news_df[["clean_text", "label"]].head()

                                          clean_text  label
0  ben stein call th circuit court committed ‘ co...      0
1  trump drop steve bannon national security coun...      1
2  puerto rico expects u lift jones act shipping ...      1
3  oops trump accidentally confirmed leaked israe...      0
4  donald trump head scotland reopen golf resort ...      1

In [84]:
news_df.to_csv("preprocessed_news.csv", index=False)

print("Preprocessed dataset saved successfully!")

Preprocessed dataset saved successfully!

In [85]:
import os

os.listdir()

['.config',
 'Fake.csv',
 'True.csv',
 'preprocessed_news.csv',
 'drive',
 'sample_data']

In [86]:
from google.colab import drive
drive.mount('/content/drive')

news_df.to_csv('/content/drive/MyDrive/preprocessed_news.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).